name: Test and Release on merge to main

on:
  push:
    branches:
     - main

jobs:
  merge_job:
    # this job will only run if the PR has been merged with 'Automated merge pull request'
    if: startsWith(github.event.head_commit.message, 'Merge pull request')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Npm 7
      run: npm i -g npm@7 --registry=https://registry.npmjs.org
      
    - run: npm ci

    - run: |
       git config --global user.email "you@example.com"
       git config --global user.name "Your Name"

    - name: Release
      run: npm run release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  # test:
  #   name: Test and release

  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [16.x]

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node-version }}

  #     - name: Install
  #       run: npm ci

  # # If tests pass, run a release
  # release:
  #   name: Release
  #   needs: [test]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: ${{ matrix.node-version }}

  #     - name: Install
  #       run: npm ci

  #     - name: Release
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  #       run: npm run release
